table Lookup_Products
	lineageTag: ecfa0b92-afe4-4074-a10d-10b4789bb6d5

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 66516752-c4e9-4975-96e6-5d761095e802
		summarizeBy: count
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: dd1bc9ac-f8f6-414d-83fd-19da9cf105bd
		summarizeBy: count
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: b0976908-076d-44e9-b5bc-6e21620d8087
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Size
		dataType: string
		lineageTag: 8ab0d0ab-0b01-43ae-9d8e-9d7529b9e48d
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	column Detail
		dataType: string
		lineageTag: 78773b95-b356-4eef-9413-758805a2b7a3
		summarizeBy: none
		sourceColumn: Detail

		annotation SummarizationSetBy = Automatic

	column SubcategoryName
		dataType: string
		lineageTag: 037d9cd1-ff6a-4b67-9190-46db01113f78
		summarizeBy: none
		sourceColumn: SubcategoryName

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: 64382284-2c6e-4f91-a712-e6ce70a843a6
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	partition Lookup_Products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\Documents\2. My Learning Space\02. Certifications\PL-300\Exercise\HPN-Dashoard-Project\data\raw\Products.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductKey", Int64.Type}, {"ProductSubcategoryKey", Int64.Type}, {"ProductName", type text}, {"Size", type text}, {"Detail", type text}, {"SubcategoryName", type text}, {"CategoryName", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

